title: Blind Apps
description: A Directory of Apps and Tools Created by Developers Who Are Blind or Have Low Vision
author: Jamal Mazrui
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 2..3